services:
  webapp:
    build:
      context: .
      dockerfile: movie_search/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - search_api
    volumes:
      - ./movie_search:/app
      - ./api/.secrets.toml:/app/api/.secrets.toml
      - ./api/settings.toml:/app/api/settings.toml
    environment:
      DJANGO_SETTINGS_MODULE: movie_search.settings

  search_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app/api
    environment:
      PYTHONPATH: /app
