DISPLAY_FIELDS = {
    "Title": True,
    "Year": True,
    "Rated": False,
    "Released": False,
    "Runtime": False,
    "Genre": False,
    "Director": False,
    "Writer": False,
    "Actors": False,
    "Plot": True,
    "Language": False,
    "Country": False,
    "Awards": False,
    "Poster": True,
    "Ratings": True,
    "Metascore": False,
    "imdbRating": False,
    "imdbVotes": False,
    "imdbID": False,
    "Type": True,
    "DVD": False,
    "BoxOffice": False,
    "Production": False,
    "Website": False,
    "Response": True,
}
