[default]
##### START SECRET VALUES #####

OMDB_API_KEY = "dummy_omdb_api_key"
API_KEY = "dummy_api_key"

##### END SECRET VALUES #####

OMDB_URL = "http://www.omdbapi.com/"
API_URL = "http://search_api:4000/v1/"  # w/o docker use http://localhost:4000/v1/
